# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: 586794478801.dkr.ecr.eu-west-2.amazonaws.com/python-flask-deployment:${TAG}
  pullPolicy: Always

imagePullSecrets:
  - name: ""
restartPolicy: Always

volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi
# Additional volumes on the output Deployment definition.
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 10005
  runAsGroup: 10005
  runAsNonRoot: true
  privileged: false
  
  #readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault
  seLinuxOptions:
    level: "s0:c123,c456"
  capabilities:
    drop:
      - ALL

service:
  name: eventBooking
  type: LoadBalancer
  protocl: TCP
  port: 3000
  targetPort: 3000

app:
  name: eventBooking

ingress:
  enabled: true
  className: "alb"
  annotations: {}
  kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: "800m"
    memory: "512Mi"
  requests:
    cpu: "500m"
    memory: "256Mi"

livenessProbe:
  exec:
        command:
        - cat
        - /tmp/healthy
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
   exec:
    command:
    - cat
    - /tmp/healthy
initialDelaySeconds: 10
periodSeconds: 10

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 25%

env:
  