# App configuration
app:
  name: event-booking-app

# Deployment configuration
deployment:
  name: python-deployment-production  # Matches your existing deployment
  replicaCount: 3
  namespace: production  # Will be overridden by helm install -n

# Image configuration
image:
  repository: 586794478801.dkr.ecr.eu-west-2.amazonaws.com/python-deployment-production  # Note typo in "deployment"
  tag: "${TAG}"  # Latest tag from your logs
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: ecr-secret  # Adjust if needed

# Resource configuration
resources:
  limits:
    cpu: "800m"
    memory: "1Gi"  # Increased from 512Mi to fix memory crash
  requests:
    cpu: "500m"
    memory: "256Mi"

# Environment variables
env:
  postgres_URL: ""  # Empty now; set a valid URL if required

# Security context (example, adjust as needed)
securityContext: {}

# Rolling update strategy
rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 25%

# Service configuration
service:
  name: event-booking-app
  type: LoadBalancer
  port: 3000
  targetPort: 3000
  selector:
    app: event-booking-app

# Ingress configuration
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
  hosts:
    - host: prod.kellerbeam.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
