# App configuration
app:
  name: event-booking-app

# Deployment configuration
deployment:
  name: python-deployment-qa-testing  # Matches your existing deployment
  replicaCount: 2
  namespace: testing  # Will be overridden by helm install -n

# Image configuration
image:
  repository: 586794478801.dkr.ecr.eu-west-2.amazonaws.com/python-deplyment-qa  # Note typo in "deplyment"
  tag: "${TAG}"  # Latest tag from your logs
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: ecr-secret  # Adjust if needed

# Resource configuration
resources:
  limits:
    cpu: "800m"
    memory: "3Gi"  # Increased from 512Mi to fix memory crash
  requests:
    cpu: "500m"
    memory: "256Mi"

# Environment variables
env:
  DATABASE_HOST: "event-booking-dev-db.c58os0ickbei.eu-west-2.rds.amazonaws.com"  # e.g., mydb.123456789012.us-east-1.rds.amazonaws.com
  DATABASE_PORT: "5432"                 # Adjust based on your DB engine
  DATABASE_NAME: "event-booking-dev-db"               # Your database name
  DATABASE_USER:
    valueFrom:
      secretKeyRef:
        name: rds!db-f94aa00f-0452-407f-a4e0-f4502712d2ea              # Matches the Kubernetes secret name
        key: username
  DATABASE_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: rds!db-f94aa00f-0452-407f-a4e0-f4502712d2ea 
        key: password
# Security context (example, adjust as needed)
securityContext: {}

# Rolling update strategy
rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 25%

# Service configuration
service:
  name: event-booking-app
  type: LoadBalancer
  port: 80
  targetPort: 3000
  selector:
    app: event-booking-app

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"  # Changed from "alb"
  annotations: {}  # Remove ALB-specific annotations
  hosts:
    - host: testing.kellerbeam.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
