# Default values for frontend.
deployment:
  name: python-deployment-qa-${environment}  # Fixed typo: "evironment" → "environment"
  namespace: testing
  replicaCount: 2

image:
  repository: 586794478801.dkr.ecr.eu-west-2.amazonaws.com/python-deployment-qa  # Fixed typo: "deplyment" → "deployment"
  pullPolicy: Always
  tag: "${TAG}"

imagePullSecrets:
  - name: ""  # Replace with actual secret name if needed

restartPolicy: Always

volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 10005
  runAsGroup: 10005
  runAsNonRoot: true
  privileged: false
  seccompProfile:
    type: RuntimeDefault
  seLinuxOptions:
    level: "s0:c123,c456"
  capabilities:
    drop:
      - ALL

service:
  name: event-booking-app
  type: LoadBalancer
  protocol: TCP  # Fixed typo: "protocl" → "protocol"
  port: 3000
  targetPort: 3000

app:
  name: event-booking-app

ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: nginx  # Fixed indentation
  hosts:
    - host: qa.kellerbeam.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: "800m"
    memory: "512Mi"
  requests:
    cpu: "500m"
    memory: "256Mi"

livenessProbe:
  exec:
    command:
      - cat
      - /tmp/healthy
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  exec:
    command:
      - cat
      - /tmp/healthy
  initialDelaySeconds: 10  # Fixed indentation
  periodSeconds: 10        # Fixed indentation

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 25%

env: {}  # Add environment variables here if needed